apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deploy
spec:
  selector:
    matchLabels:
      app: keycloak-deploy
  template:
    metadata:
      labels:
        app: keycloak-deploy
    spec:
      containers:
      - name: keycloak-deploy
        image: quay.io/keycloak/keycloak:17.0.1
        args:
        - start-dev
        - --auto-build
        - --hostname=localhost
        - --https-certificate-file=/certs/tls.crt
        - --https-certificate-key-file=/certs/tls.key
        - --spi-theme-static-max-age=-1
        - --spi-theme-cache-themes=false
        - --spi-theme-cache-templates=false
        env:
        - name: KC_DB
          value: postgres
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-password
              key: password
        - name: KC_DB_URL_DATABASE
          value: postgres
        - name: KC_DB_URL_HOST
          value:  postgres-svc
        - name: KC_DB_USERNAME
          value: postgres
        - name: KC_HOSTNAME_STRICT_HTTPS
          value: "false"
        - name: KEYCLOAK_ADMIN
          valueFrom:
            secretKeyRef:
              name: keycloak-admin-password
              key: username
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-admin-password
              key: password
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        volumeMounts:
        - name: keycloak-certs-vlm
          mountPath: "/certs"
          readOnly: true
      volumes:
      - name: keycloak-certs-vlm
        secret:
          secretName: keycloak-ssl-certs
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-svc
spec:
  selector:
    app: keycloak-deploy
  ports:
    - name: https
      port: 80
      targetPort: 8443